stages:
  - test
  - build
  - release

default:
  before_script:
    - npm install

include:
  - component: gitlab.com/Profidev/gitlab-lint/gitlab-ci@v0.1.4
    inputs:
      stage: test
      prettier: true
      access_token: $TOKEN
      tsc: true
      auto_fix: true
      commit: true

build_image:
  stage: build
  image: docker:latest
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG || $CI_MERGE_REQUEST_ID'
  services:
    - docker:dind
  before_script: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY;
    # tag is CI_COMMIT_REF_NAME, which is main or the tag name for branches use CI_COMMIT_REF_SLUG
    - if [[ "$CI_COMMIT_BRANCH" == "main" || -n "$CI_COMMIT_TAG" ]]; then
      export IMAGE_TAG=$CI_COMMIT_REF_NAME;
      else
      export IMAGE_TAG=$CI_COMMIT_REF_SLUG;
      fi
    - docker context create builder
    - docker buildx create builder --driver docker-container --use
    - docker buildx build -t $CI_REGISTRY_IMAGE/gitlab-lint:$IMAGE_TAG --load --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/gitlab-lint:cache --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/gitlab-lint:cache,mode=max .
    - if [[ "$CI_COMMIT_BRANCH" == "main" || -n "$CI_COMMIT_TAG" ]]; then
      echo "Pushing Docker image to registry...";
      docker push $CI_REGISTRY_IMAGE/gitlab-lint:$IMAGE_TAG;
      else
      echo "Not pushing Docker image to registry, skipping...";
      fi

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  before_script: ""
  needs:
    - build_image
  rules:
    - if: $CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components in $CI_PROJECT_PATH"
